In [1]:
import pandas as pd

# 预处理临床数据特征

In [128]:
df_clin = pd.read_table('./Clinical.tsi', header=None)
df_clin = df_clin.T
columns = df_clin.iloc[0,:].values
df_clin = df_clin.iloc[1:,:]
df_clin.columns = columns
df_clin = df_clin[~df_clin.overall_survival.isna()]
df_clin

,attrib_name,years_to_birth,Tumor_purity,histological_type,gender,radiation_therapy,race,ethnicity,overall_survival,status,overallsurvival
1,TCGA.06.6391,44,0.836,untreatedprimary(denovo)gbm,female,no,white,nothispanicorlatino,45,1,"45,1"
2,TCGA.19.A6J4,68,0.6736,glioblastomamultiforme(gbm),male,NaN,blackorafricanamerican,nothispanicorlatino,121,1,"121,1"
3,TCGA.06.1806,47,0.7913,glioblastomamultiforme(gbm),male,yes,white,nothispanicorlatino,466,1,"466,1"
4,TCGA.06.5408,54,0.8635,untreatedprimary(denovo)gbm,female,yes,white,nothispanicorlatino,357,1,"357,1"
5,TCGA.06.5410,72,0.3396,untreatedprimary(denovo)gbm,female,no,white,nothispanicorlatino,108,1,"108,1"
...,...,...,...,...,...,...,...,...,...,...,...
591,TCGA.76.6283,71,0.9779,glioblastomamultiforme(gbm),female,NaN,white,nothispanicorlatino,165,1,"165,1"
592,TCGA.76.6660,73,0.7707,glioblastomamultiforme(gbm),male,NaN,white,nothispanicorlatino,114,1,"114,1"
593,TCGA.81.5910,64,0.7913,untreatedprimary(denovo)gbm,male,no,white,NaN,49,1,"49,1"
594,TCGA.81.5911,33,0.7913,untreatedprimary(denovo)gbm,male,yes,white,NaN,539,0,"539,0"
595,TCGA.87.5896,50,0.888,untreatedprimary(denovo)gbm,female,yes,white,nothispanicorlatino,800,0,"800,0"

# 读取基因表达特征

In [13]:
df_expr = pd.read_table('./Expression_RSEM_log2.cct.gz', compression='gzip')

df_expr

,attrib_name,TCGA.02.0001,TCGA.02.0003,TCGA.02.0004,TCGA.02.0007,TCGA.02.0009,TCGA.02.0010,TCGA.02.0011,TCGA.02.0014,TCGA.02.0015,...,TCGA.76.4932,TCGA.76.4934,TCGA.76.4935,TCGA.76.6191,TCGA.76.6192,TCGA.76.6193,TCGA.76.6282,TCGA.76.6285,TCGA.81.5910,TCGA.87.5896
0,AACS,6.5006,6.5392,7.3778,7.1869,7.6750,7.9960,8.3551,6.8401,6.3491,...,5.8965,6.3478,6.1927,7.2218,7.5393,6.9078,7.0076,7.6763,7.1052,7.2302
1,FSTL1,8.7297,9.7944,12.0596,4.9451,10.8401,8.9316,4.2406,7.7385,10.7565,...,8.1148,8.8745,9.9205,10.1363,9.8328,11.0918,10.7895,9.6826,9.8474,10.4376
2,ELMO2,5.5114,6.2140,7.0517,5.2304,6.6207,7.5524,6.7073,7.2623,7.1187,...,7.3827,6.8193,6.6757,7.7135,7.6458,7.8877,7.5698,7.0198,7.5335,7.9569
3,CREB3L1,4.8830,4.8363,6.1124,5.8186,5.3332,6.0873,4.8655,4.5245,4.8251,...,4.6810,5.6369,5.3315,5.0622,5.5533,4.6878,5.3670,4.6857,6.1549,6.8131
4,RPS11,10.9848,10.8112,10.4364,10.4773,10.6373,11.0015,10.6859,10.6613,10.2849,...,10.9302,10.4001,10.3514,10.6369,10.5655,10.4751,10.5730,10.4392,10.6853,10.3156
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12037,RPS27,12.9119,13.4194,13.2296,13.5751,13.2870,13.4803,13.4748,13.2551,12.8173,...,13.1120,12.2189,12.5645,13.3991,13.2774,13.3434,13.1790,13.5058,13.3282,13.3594
12038,SNRPD2,11.8723,11.1097,11.3210,11.6656,11.4804,10.9516,11.5424,11.6901,11.5672,...,11.5995,10.7257,10.9091,11.3819,10.6221,10.1613,10.8780,10.5722,11.1809,10.2248
12039,SLC39A6,6.8677,8.1478,8.5192,9.1899,8.5564,9.2099,8.4376,10.2048,9.5014,...,8.5249,9.0474,8.8416,10.1541,9.3788,9.2649,8.8396,8.8872,9.8162,9.8607
12040,CTSC,10.3541,11.3674,10.3795,11.4782,10.4047,8.4179,10.2427,9.1884,10.5965,...,9.5624,9.1543,8.8670,9.3234,9.3672,10.7787,9.9779,9.4662,8.0059,8.0687
12041,AQP7,4.7099,4.1964,3.7339,4.3231,4.6391,4.1673,4.1795,4.0589,4.0949,...,4.0070,3.8599,3.7730,3.7498,3.6963,3.6473,3.7119,3.6692,3.8327,3.7023

# 读取突变数据特征

In [33]:
df_mut = pd.read_table('./Mutation.cbt')
df_mut

,attrib_name,TCGA.06.5411,TCGA.06.2558,TCGA.14.0813,TCGA.27.1833,TCGA.06.0137,TCGA.06.0173,TCGA.06.6701,TCGA.28.5207,TCGA.06.6695,...,TCGA.06.0130,TCGA.12.0615,TCGA.06.0167,TCGA.27.1836,TCGA.06.0240,TCGA.06.0881,TCGA.27.2518,TCGA.08.0386,TCGA.06.0139,TCGA.06.0178
0,A1CF,0,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,A2BP1,0,0,0,0,1,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
2,AADACL4,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,ABCA10,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,ABCA13,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1463,ZNF99,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1464,ZP4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1465,ZPBP,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1466,ZSCAN1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1467,ZSCAN29,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0

# 读取CNV数据特征

In [14]:
df_cnv = pd.read_table('./CNV.cct.gz', compression='gzip')
df_cnv

,attrib_name,TCGA.02.0001,TCGA.02.0003,TCGA.02.0006,TCGA.02.0007,TCGA.02.0009,TCGA.02.0010,TCGA.02.0011,TCGA.02.0014,TCGA.02.0015,...,TCGA.76.6662,TCGA.76.6663,TCGA.76.6664,TCGA.81.5910,TCGA.81.5911,TCGA.87.5896,TCGA.OX.A56R,TCGA.RR.A6KA,TCGA.RR.A6KB,TCGA.RR.A6KC
0,ACAP3,0.242,0.007,0.005,-0.072,0.048,-0.094,0.013,-0.029,-0.222,...,-0.003,-0.003,-0.001,0.052,-0.020,-0.916,0.152,-0.047,0.027,-0.016
1,ACTRT2,0.242,0.007,0.005,-0.072,0.048,-0.094,0.013,-0.029,-0.222,...,-0.003,-0.003,-0.001,0.052,-0.020,-0.916,0.152,-0.047,0.027,-0.016
2,AGRN,0.242,0.007,0.005,-0.072,0.048,-0.094,0.013,-0.029,-0.222,...,-0.003,-0.003,-0.001,0.052,-0.020,-0.916,0.152,-0.047,0.027,-0.016
3,ANKRD65,0.242,0.007,0.005,-0.072,0.048,-0.094,0.013,-0.029,-0.222,...,-0.003,-0.003,-0.001,0.052,-0.020,-0.916,0.152,-0.047,0.027,-0.016
4,ATAD3A,0.242,0.007,0.005,-0.072,0.048,-0.094,0.013,-0.029,-0.222,...,-0.003,-0.003,-0.001,0.052,-0.020,-0.916,0.152,-0.047,0.027,-0.016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24771,IL9R|ENSG00000124334.12,0.076,-0.071,-0.052,-0.184,-0.058,-0.096,-0.199,-0.103,-0.069,...,0.009,-0.003,-0.006,-0.083,-0.086,-0.048,-0.178,0.019,-0.023,-0.007
24772,SPRY3|ENSG00000168939.6,0.076,-0.071,-0.052,-0.184,-0.058,-0.096,-0.199,-0.103,-0.069,...,0.009,-0.003,-0.006,-0.083,-0.086,-0.048,-0.178,0.019,-0.023,-0.007
24773,VAMP7|ENSG00000124333.10,0.076,-0.071,-0.052,-0.184,-0.058,-0.096,-0.199,-0.103,-0.069,...,0.009,-0.003,-0.006,-0.083,-0.086,-0.048,-0.178,0.019,-0.023,-0.007
24774,WASH6P|ENSG00000182484.10,0.076,-0.071,-0.052,-0.184,-0.058,-0.096,-0.199,-0.103,-0.069,...,0.009,-0.003,-0.006,-0.083,-0.086,-0.048,-0.178,0.019,-0.023,-0.007
24775,WASIR1|ENSG00000185203.7,0.076,-0.071,-0.052,-0.184,-0.058,-0.096,-0.199,-0.103,-0.069,...,0.009,-0.003,-0.006,-0.083,-0.086,-0.048,-0.178,0.019,-0.023,-0.007

# 读取甲基化数据特征

这个27K含义是说一张芯片上测了27000个甲基化位点，450K表示测了450000个位点

HM27K：只有启动子区域的甲基化

HM450K：包括了启动子区域、基因Body区域等。

In [16]:
df_met = pd.read_table('./Methylation_HM450K.cct.gz', compression='gzip')
df_met

,attrib_name,TCGA.06.0125,TCGA.06.0152,TCGA.06.0171,TCGA.06.0190,TCGA.06.0210,TCGA.06.0211,TCGA.06.0221,TCGA.06.0650,TCGA.06.1804,...,TCGA.76.6662,TCGA.76.6663,TCGA.76.6664,TCGA.81.5910,TCGA.81.5911,TCGA.87.5896,TCGA.OX.A56R,TCGA.RR.A6KA,TCGA.RR.A6KB,TCGA.RR.A6KC
0,RBL2,-0.4848,-0.4830,-0.4845,-0.4848,-0.4842,-0.4810,-0.4872,-0.4892,-0.4871,...,-0.4836,-0.4838,-0.4890,-0.4871,-0.4864,-0.4856,-0.4878,-0.4845,-0.4849,-0.4855
1,VDAC3,-0.4680,-0.4606,-0.4653,-0.4532,-0.4467,-0.4173,-0.4286,-0.4740,-0.4597,...,-0.2680,-0.2843,-0.4527,-0.4719,-0.4485,-0.4633,-0.4569,-0.3266,-0.4461,-0.4664
2,ACTN1,-0.0822,0.1367,0.0464,0.0269,-0.0001,0.1109,0.1314,0.1106,-0.1177,...,0.1460,0.1429,0.0154,0.0880,-0.0036,0.2745,0.0288,0.0515,0.0472,-0.1586
3,ATP2A1,0.2155,0.0414,-0.1607,0.2335,-0.0096,0.2584,0.2730,0.1867,0.0835,...,0.3887,0.3194,0.2169,-0.0072,0.4050,0.2730,0.0859,0.0808,0.2029,0.2288
4,SFRP1,-0.4082,-0.4257,0.0666,-0.4350,0.0953,0.0943,-0.4136,-0.4500,0.1215,...,-0.0289,-0.0148,0.1953,-0.4396,0.2349,-0.0433,-0.4502,-0.0716,-0.4492,-0.1842
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20109,MIR637,0.3677,0.2566,0.3824,0.3819,0.3768,0.3639,0.3764,0.3481,0.3896,...,0.3816,0.3940,0.3617,0.3251,0.3903,0.3710,0.3679,0.3264,0.3481,0.3471
20110,LOC100130932,0.4383,0.4334,0.3916,0.4147,0.2446,0.4221,0.4369,0.4258,0.4301,...,0.4060,0.4289,0.4324,0.4153,0.4416,0.4604,0.4221,0.3348,0.2776,0.4173
20111,GOLGA8F,-0.0621,-0.1592,-0.0838,-0.0392,-0.0920,-0.0614,-0.1016,-0.0511,-0.0610,...,0.0440,0.0208,-0.0947,-0.1274,0.0660,-0.1154,-0.0324,0.0206,-0.0268,-0.0916
20112,GOLGA8G,-0.0621,-0.1592,-0.0838,-0.0392,-0.0920,-0.0614,-0.1016,-0.0511,-0.0610,...,0.0440,0.0208,-0.0947,-0.1274,0.0660,-0.1154,-0.0324,0.0206,-0.0268,-0.0916
20113,MIR7-1,-0.4394,-0.4348,-0.4190,-0.4266,-0.3858,-0.4202,-0.4326,-0.2794,-0.3589,...,-0.4323,-0.4322,-0.4131,-0.2652,-0.4318,-0.3614,NaN,-0.1650,-0.2777,-0.1210

In [17]:
# 考虑到样本量，这里采用27K
df_met = pd.read_table('./Methylation_HM27.cct.gz', compression='gzip')
df_met

,attrib_name,TCGA.02.0001,TCGA.02.0003,TCGA.02.0006,TCGA.02.0007,TCGA.02.0009,TCGA.02.0010,TCGA.02.0011,TCGA.02.0014,TCGA.02.0021,...,TCGA.32.4213,TCGA.32.4719,TCGA.41.2571,TCGA.41.2572,TCGA.41.2573,TCGA.41.2575,TCGA.41.3392,TCGA.41.3393,TCGA.41.3915,TCGA.41.4097
0,ATP2A1,0.3261,0.1966,0.1365,0.3267,0.3360,0.1871,-0.4454,0.1633,0.2335,...,0.0676,0.1288,0.1129,0.0977,-0.1000,-0.4353,-0.1843,0.2044,-0.0249,0.3004
1,SLMAP,-0.4759,-0.4829,-0.4791,-0.4822,-0.4820,-0.4752,-0.4803,-0.4817,-0.4784,...,-0.4836,-0.4885,-0.4863,-0.4878,-0.4864,-0.4853,-0.4874,-0.4809,-0.4856,-0.4871
2,MEOX2,-0.4585,-0.3961,-0.4392,-0.4745,-0.4587,-0.4627,-0.4093,-0.0005,-0.4560,...,-0.4774,-0.4435,-0.4772,-0.4582,-0.4715,-0.4732,-0.4676,-0.4700,-0.4683,-0.4452
3,HOXD3,-0.0915,-0.4494,-0.4456,0.1464,-0.3111,-0.1366,-0.4326,0.4489,-0.4358,...,-0.2412,0.0824,-0.0080,-0.0950,-0.1881,0.2135,-0.4177,0.0912,0.0760,-0.0148
4,PANX1,-0.3798,-0.4289,-0.3792,-0.3042,-0.3700,-0.3640,-0.3964,-0.3763,-0.3747,...,-0.4089,-0.3944,-0.4222,-0.4209,-0.4138,-0.4350,-0.4255,-0.3737,-0.4043,-0.4092
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13769,TRMT6,-0.4777,-0.4869,-0.4855,-0.4830,-0.4787,-0.4808,-0.4772,-0.4827,-0.4853,...,-0.4468,-0.4592,-0.4906,-0.4453,-0.4884,-0.4892,-0.4885,-0.4448,-0.4429,-0.4500
13770,ATXN7,-0.4327,-0.4462,-0.4377,-0.3596,-0.4449,-0.4584,-0.4639,-0.4338,-0.4272,...,-0.4714,-0.4687,-0.4703,-0.4825,-0.4692,-0.4758,-0.4771,-0.4717,-0.4793,-0.4784
13771,POLDIP2,-0.4546,-0.4537,-0.4618,-0.4561,-0.4617,-0.4547,-0.4582,-0.4627,-0.4608,...,-0.4814,-0.4810,-0.4703,-0.4838,-0.4669,-0.4739,-0.4572,-0.4809,-0.4855,-0.4841
13772,TMEM199,-0.4546,-0.4537,-0.4618,-0.4561,-0.4617,-0.4547,-0.4582,-0.4627,-0.4608,...,-0.4814,-0.4810,-0.4703,-0.4838,-0.4669,-0.4739,-0.4572,-0.4809,-0.4855,-0.4841
13773,KCNRG,0.4108,0.3771,0.3432,0.1972,0.4293,0.4091,0.3921,0.4173,0.4087,...,0.2153,0.4281,0.2807,0.3677,0.3671,0.3390,0.3563,0.3199,0.3427,0.3354

# 预处理

## 查看共有多少样本，同时具备临床、基因表达、CNV、Mut和甲基化的数据

不考虑突变，共有254个样本同时存在

考虑了突变，仅109个样本。

故，本次试验，多组学数据只采用临床特征、基因表达特征、拷贝数变异特征、甲基化特征

In [129]:
smp_clin = df_clin.attrib_name.to_list()
smp_expr = list(df_expr.columns.values[1:])
smp_mut = list(df_mut.columns.values[1:])
smp_cnv = list(df_cnv.columns.values[1:])
smp_met = list(df_met.columns.values[1:])

print('Clin: {}; Expr: {} ;CNV: {}; Mut: {} ;Met: {}'.format(len(smp_clin), len(smp_expr), len(smp_cnv),len(smp_mut) ,len(smp_met)))

Clin: 567; Expr: 528 ;CNV: 577; Mut: 283 ;Met: 285

In [130]:
smp_tmp = set(smp_clin).intersection(set(smp_expr))
print(len(smp_tmp))

smp_tmp = set(smp_tmp).intersection(set(smp_cnv))
print(len(smp_tmp))

smp_tmp = set(smp_tmp).intersection(set(smp_met))
print(len(smp_tmp))

smp_tmp = set(smp_tmp).intersection(set(smp_mut))
print(len(smp_tmp))

500
482
254
109

In [131]:
# 获取只考虑三种组学的样本名
smp_tmp = set(smp_clin).intersection(set(smp_expr))
smp_tmp = set(smp_tmp).intersection(set(smp_cnv))
smp_tmp = set(smp_tmp).intersection(set(smp_met))
extracted_smp = smp_tmp

## 根据样本名提取数据

In [132]:
df_clin_extracted = df_clin[df_clin.attrib_name.isin(extracted_smp)]
df_expr_extracted = df_expr[['attrib_name'] + list(extracted_smp)]
df_cnv_extracted = df_cnv[['attrib_name'] + list(extracted_smp)]
df_met_extracted = df_met[['attrib_name'] + list(extracted_smp)]

## 查看LTS和Non-LTS的样本量

In [134]:
df_clin_extracted.status = df_clin_extracted.status.astype('int')
df_clin_extracted.overall_survival = df_clin_extracted.overall_survival.astype('int')
print(df_clin_extracted[(df_clin_extracted.overall_survival < 365*2) & (df_clin_extracted.status == 1)].shape)
print(df_clin_extracted[df_clin_extracted.overall_survival > 365*2].shape)

(170, 11)
(50, 11)

C:\Users\liangbilin\AppData\Local\Temp\ipykernel_14352\264798488.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clin_extracted.status = df_clin_extracted.status.astype('int')
C:\Users\liangbilin\AppData\Local\Temp\ipykernel_14352\264798488.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clin_extracted.overall_survival = df_clin_extracted.overall_survival.astype('int')

## 查看三种组学的基因重叠情况

In [135]:
print("Expr: {}; CNV: {}; Met: {}".format(df_expr_extracted.shape[0], df_cnv_extracted.shape[0], df_met_extracted.shape[0]))

Expr: 12042; CNV: 24776; Met: 13774

In [136]:
# 同时在三种组学中都存在的基因数

df_cnv_extracted[(df_cnv_extracted.attrib_name.isin(df_met_extracted.attrib_name)) &
                 (df_cnv_extracted.attrib_name.isin(df_expr_extracted.attrib_name))
                ].shape

(8967, 255)

In [137]:
genes = df_cnv_extracted[(df_cnv_extracted.attrib_name.isin(df_met_extracted.attrib_name)) &
                 (df_cnv_extracted.attrib_name.isin(df_expr_extracted.attrib_name))
                ].attrib_name.values
genes

array(['ATAD3A', 'C1orf159', 'CPSF3L', ..., 'SCO2', 'TRABD', 'ZBED4'],
      dtype=object)

In [138]:
# 根据基因名进行数据清洗

df_expr_extracted = df_expr_extracted[df_expr_extracted.attrib_name.isin(genes)]
df_cnv_extracted = df_cnv_extracted[df_cnv_extracted.attrib_name.isin(genes)]
df_met_extracted = df_met_extracted[df_met_extracted.attrib_name.isin(genes)]

print("Expr: {}; CNV: {}; Met: {}".format(df_expr_extracted.shape[0], df_cnv_extracted.shape[0], df_met_extracted.shape[0]))

Expr: 8967; CNV: 8967; Met: 8967

## 基因名转为Entrez-id

In [98]:
import mygene

In [180]:
 mg = mygene.MyGeneInfo()
df_tmp = mg.querymany(df_expr_extracted.attrib_name.to_list(), 
                      scopes='symbol', 
                      fields='entrezgene', 
                      species='human', 
                      as_dataframe=True)
df_tmp

querying 1-1000...done.
querying 1001-2000...done.
querying 2001-3000...done.
querying 3001-4000...done.
querying 4001-5000...done.
querying 5001-6000...done.
querying 6001-7000...done.
querying 7001-8000...done.
querying 8001-8967...done.
Finished.
128 input query terms found dup hits:
	[('EMX2', 2), ('SNX6', 2), ('UPF3A', 2), ('CAMSAP1', 2), ('KCTD2', 2), ('DUSP10', 2), ('RNF126', 2),
393 input query terms found no hit:
	['MTERF', 'ATP5G2', 'PROSC', 'KIAA1199', 'TMEM180', 'CCDC41', 'RARRES3', 'KIAA0100', 'C11orf73', 'C2
Pass "returnall=True" to return complete lists of duplicate or missing query terms.

           _id     _score entrezgene notfound
query
AACS     65985  87.839140      65985      NaN
FSTL1    11167  89.625930      11167      NaN
ELMO2    63916  87.657300      63916      NaN
RPS11     6205  65.451420       6205      NaN
PNMA1     9240  94.998420       9240      NaN
...        ...        ...        ...      ...
RPS27     6232  91.071670       6232      NaN
SNRPD2    6633  88.733230       6633      NaN
SLC39A6  25800  87.738100      25800      NaN
CTSC      1075  87.529020       1075      NaN
AQP7       364  90.476326        364      NaN

[9133 rows x 4 columns]

In [181]:
# 删除异常情况
df_tmp = df_tmp[~df_tmp.entrezgene.isna()]

df_tmp = df_tmp[df_tmp.entrezgene != "7795"]

In [182]:
def f(x):
    if x in df_tmp.index.values:
        return df_tmp.loc[x, 'entrezgene']
    else:
        return None
    
df_expr_extracted.attrib_name = df_expr_extracted.attrib_name.map(f)
df_cnv_extracted.attrib_name = df_cnv_extracted.attrib_name.map(f)
df_met_extracted.attrib_name = df_met_extracted.attrib_name.map(f)

In [183]:
df_expr_extracted = df_expr_extracted[~df_expr_extracted.attrib_name.isna()]
df_cnv_extracted = df_cnv_extracted[~df_cnv_extracted.attrib_name.isna()]
df_met_extracted = df_met_extracted[~df_met_extracted.attrib_name.isna()]

In [184]:
print("Expr: {}; CNV: {}; Met: {}".format(df_expr_extracted.shape[0], df_cnv_extracted.shape[0], df_met_extracted.shape[0]))

Expr: 8574; CNV: 8574; Met: 8574

## 输出

In [186]:
df_expr_extracted.to_csv('../../GBM.expression.tsv.gz', index=False, sep='\t', compression='gzip')
df_cnv_extracted.to_csv('../../GBM.cnv.tsv.gz', index=False, sep='\t', compression='gzip')
df_met_extracted.to_csv('../../GBM.met.tsv.gz', index=False, sep='\t', compression='gzip')

# PPI的删除基因

In [192]:
etrez_genes = [int(i) for i in df_expr_extracted.attrib_name.values]

In [120]:
df_ppi = pd.read_csv('../../string.csv.gz', compression='gzip')
df_ppi

                src   dest  score
0               381   5137    155
1               381   5062    197
2               381   9609    222
3               381   2889    181
4               381   6612    270
...             ...    ...    ...
10866757  105369274  54429    190
10866758  105369274    156    600
10866759  105369274  51764    600
10866760  105369274   2774    600
10866761  105369274  25893    248

[10866762 rows x 3 columns]

In [194]:
df_ppi = df_ppi[(df_ppi.src.isin(etrez_genes)) & (df_ppi.dest.isin(etrez_genes))]

In [195]:
df_ppi.to_csv('../../string_clin.csv.gz', compression='gzip')